### ISSUE TITLE
Database implimentation

### ISSUE THREAD

**Issue by moonmeister** [moonmeister/cs162library#13]
Need to read and write from databases for user users and their books.

**Comment by moonmeister** [comment]
@bkilada I'm assigning this to you since you did all the original file implementation. I'll work on some of the due dates and overdue stuff since I know what I want to do for that.

**Comment by moonmeister** [comment]
see branch "databases"

**Comment by bkilada** [comment]
Cool, I'll get on it. Sorry, been busy at a birthday party.
