### ISSUE TITLE
Checkin/checkout functionality. 

### ISSUE THREAD

**Issue by moonmeister** [moonmeister/cs162library#14]
Please review my modification of the search implementation. notice that it loops as long as the curBook is set. thus checkout will function by moving the cubook to the users book list and set curboook to 0. then to check it in you search find the book in their list and delete the obj.

**Comment by bkilada** [comment]
Done. Please review my pull-request to merge Check Out branch into Master. Feel free to modify code...I've had a long day and I'm not confident the way I did it was best. But hey, it works.
