### ISSUE TITLE
Clear screen

### ISSUE THREAD

**Issue by moonmeister** [moonmeister/cs162library#20]
@bkilada  Can you confirm the  _system("clear");_ command works on your machine for clearing the console screen. This might be a good tool other than a couple new line for making the gui look nice.

**Comment by bkilada** [comment]
That doesn't work, though this does: 
cout << "\033[2J\033[1;1H";

See [http://stackoverflow.com/questions/4062045/clearing-terminal-in-linux-with-c-code](http://stackoverflow.com/questions/4062045/clearing-terminal-in-linux-with-c-code).

**Comment by moonmeister** [comment]
BOOM! @bkilada that worked for me too. that'll make the interface nice and clean feeling. We can build that in as we go forward and when we review the gui can add it to previous things.

**Comment by bkilada** [comment]
Sounds good. :) I would recommend adding a "ClearConsole()" function.

**Comment by moonmeister** [comment]
Good idea...we can do that soon.

**Comment by moonmeister** [comment]
Implemented in the gui branch

**Comment by moonmeister** [comment]
#25
